- name: Install Neovim
  community.general.homebrew:
    name: neovim
    state: present

- name: Install Tmux
  community.general.homebrew:
    name: tmux
    state: present

- name: Install Yabai
  community.general.homebrew:
    name: koekeishiya/formulae/yabai
    state: present

- name: Install iterm2
  community.general.homebrew:
    name: iterm2
    state: present
- name: Install skhd
  community.general.homebrew:
    name: skhd
    status: present
